# Generated by Django 5.1.3 on 2025-01-22 16:18

import facturas.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.CharField(max_length=100, unique=True)),
                ('mes_contable', models.DateField(help_text='Formato: YYYY-MM')),
                ('unidad_negocio', models.CharField(max_length=255)),
                ('aprobador_nombre', models.CharField(max_length=255)),
                ('aprobador_rut', models.CharField(max_length=50)),
                ('aprobador_dos_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('aprobador_dos_rut', models.CharField(blank=True, max_length=50, null=True)),
                ('factura', models.FileField(upload_to=facturas.utils.rename_factura)),
                ('fecha_generado', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facturas_solicitud',
            },
        ),
    ]
