# Generated by Django 5.1.3 on 2025-01-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='aprobador_dos_nombre',
            new_name='aprobadorDosNombre',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='aprobador_dos_rut',
            new_name='aprobadorDosRut',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='aprobador_nombre',
            new_name='aprobadorNombre',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='aprobador_rut',
            new_name='aprobadorRut',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='fecha_generado',
            new_name='fechaGenerado',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='fecha_vencimiento',
            new_name='fechaVencimiento',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='mes_contable',
            new_name='mesContable',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='unidad_negocio',
            new_name='unidadNegocio',
        ),
    ]
