# Generated by Django 5.1.3 on 2025-01-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_rename_aprobador_dos_nombre_solicitud_aprobadordosnombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='anioMesContable',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='centroCosto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='glosa',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='motoNave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='numeroServicio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='pagado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='pendiente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='aprobadorRut',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='mesContable',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
