# Generated by Django 5.1.3 on 2025-01-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_solicitud_aniomescontable_solicitud_centrocosto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='mesContable',
            field=models.CharField(max_length=100),
        ),
    ]
