# Generated by Django 5.1.3 on 2025-01-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_alter_solicitud_mescontable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='centroCosto',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='motoNave',
        ),
    ]
