# Generated by Django 5.1.3 on 2025-01-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0005_remove_solicitud_centrocosto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fechaAprobacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fechaDosAprobacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
