# Generated by Django 5.1.3 on 2025-01-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0006_solicitud_fechaaprobacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='numeroServicio',
        ),
    ]
