# Generated by Django 5.1.3 on 2025-01-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0007_remove_solicitud_numeroservicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='aprobadorDosNombre',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='aprobadorDosRut',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='aprobadorNombre',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='glosa',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='aprobador',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='aprobadorDos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='aprobadorRutDos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='glosaAprobador',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='glosaAprobadorDos',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
