# Generated by Django 5.1.3 on 2025-01-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0008_remove_solicitud_aprobadordosnombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='aprobadorRutTres',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='aprobadorTres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='glosaAprobadorTres',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='aprobadorDos',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='aprobadorRutDos',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
