# Generated by Django 5.1.3 on 2025-01-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0009_solicitud_aprobadorruttres_solicitud_aprobadortres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fechaTresAprobacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
