# Generated by Django 5.1.3 on 2025-01-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0010_solicitud_fechatresaprobacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='aprobador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='aprobadorRut',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
