# Generated by Django 5.1.3 on 2025-01-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0011_alter_solicitud_aprobador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='visadoAprobador',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='visadoAprobadorDos',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='visadoAprobadorTres',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
