# Generated by Django 5.1.3 on 2024-11-07 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendidor', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=10)),
                ('aprobadorJefatura', models.CharField(blank=True, max_length=200, null=True)),
                ('aprobadorAdmin', models.CharField(max_length=200)),
                ('referencia', models.CharField(max_length=200)),
                ('montoAsignado', models.IntegerField(blank=True, null=True)),
                ('fechaAsignado', models.DateField()),
                ('centroCosto', models.CharField(max_length=50)),
                ('motoNave', models.PositiveIntegerField(choices=[(1, 'NO'), (2, 'SI')], default=1)),
                ('totalRendido', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'rendiciones_fondo',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreComprobante', models.CharField(max_length=100)),
                ('numeroComprobante', models.CharField(max_length=100)),
                ('tipoComprobante', models.CharField(max_length=20)),
                ('proveedor', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fechaGasto', models.DateField()),
                ('montoGasto', models.IntegerField()),
                ('visadoJefe', models.CharField(blank=True, max_length=20, null=True)),
                ('visadoAdmin', models.CharField(blank=True, max_length=20, null=True)),
                ('idfondo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_gastos', to='api_rendiciones.fondo')),
            ],
            options={
                'db_table': 'rendiciones_gasto',
            },
        ),
    ]
