# Generated by Django 5.1.3 on 2024-11-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rendiciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondo',
            name='correo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
