# Generated by Django 5.1.3 on 2024-11-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rendiciones', '0002_fondo_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fondo',
            name='correo',
        ),
    ]
