# Generated by Django 5.1.3 on 2024-11-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rendiciones', '0003_remove_fondo_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fondo',
            name='motoNave',
            field=models.BooleanField(default=False),
        ),
    ]
