# Generated by Django 5.1.3 on 2024-11-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rendiciones', '0004_alter_fondo_motonave'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='tipoGasto',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
