# Generated by Django 5.1.3 on 2024-11-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rendiciones', '0006_alter_gasto_nombrecomprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='nombreComprobante',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
