# Generated by Django 5.1.3 on 2024-11-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rendiciones', '0008_alter_gasto_nombrecomprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='numeroServicio',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
