# Generated by Django 5.1.3 on 2024-11-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rendiciones', '0009_gasto_numeroservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='numeroServicio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
