# Generated by Django 5.1.3 on 2024-11-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rendiciones', '0010_alter_gasto_numeroservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fondo',
            name='centroCosto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
