# Generated by Django 5.1.3 on 2024-12-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rendiciones', '0011_alter_fondo_centrocosto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondo',
            name='asignacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
