# Generated by Django 5.1.3 on 2024-12-16 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rendiciones', '0012_fondo_asignacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_empresa', models.IntegerField(default=0)),
                ('saldo_rendidor', models.IntegerField(default=0)),
                ('idfondo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='neteo', to='api_rendiciones.fondo')),
            ],
            options={
                'db_table': 'rendiciones_neteo',
            },
        ),
    ]
