# Generated by Django 5.1.3 on 2024-12-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rendiciones', '0014_centrocostos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='centrocostos',
            table='centrocostos',
        ),
    ]
