# Generated by Django 5.1.3 on 2025-01-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rendiciones', '0015_alter_centrocostos_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='numeroComprobante',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='numeroServicio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='proveedor',
            field=models.CharField(max_length=100),
        ),
    ]
