# Generated by Django 5.1.3 on 2025-01-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correoUser', models.CharField(max_length=100, unique=True)),
                ('codigoRol', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idViaje', models.IntegerField()),
                ('idUsuario', models.CharField(max_length=50)),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('contactoUsuario', models.EmailField(max_length=50)),
                ('fecha', models.CharField(max_length=50)),
                ('dia', models.IntegerField()),
                ('horaActividadI', models.CharField(max_length=5)),
                ('horaActividadT', models.CharField(max_length=5)),
                ('cliente', models.CharField(max_length=50)),
                ('lugar', models.CharField(max_length=50)),
                ('participantes', models.CharField(max_length=100)),
                ('motivo', models.CharField(max_length=100)),
                ('resultadoEsperado', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Jerarquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField()),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('idJefe', models.IntegerField(blank=True, null=True)),
                ('nombreJefe', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRegion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRol', models.CharField(max_length=50)),
                ('codigoRol', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('oficina', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('dirSalida', models.CharField(max_length=50)),
                ('dirDestino', models.CharField(max_length=50)),
                ('fechaSolicitud', models.DateField()),
                ('fechaDeparto', models.DateField()),
                ('fechaRetorno', models.DateField()),
                ('horaIda', models.CharField(max_length=10)),
                ('horaVuelta', models.CharField(max_length=10)),
                ('transportes', models.CharField(max_length=100)),
                ('hotel', models.CharField(max_length=50)),
                ('cantnoches', models.PositiveIntegerField()),
                ('costonoche', models.PositiveIntegerField()),
                ('costoAlimento', models.PositiveIntegerField()),
                ('costoHospedaje', models.PositiveIntegerField()),
                ('costoTransporte', models.PositiveIntegerField()),
                ('costoTotal', models.PositiveIntegerField()),
                ('tipoMoneda', models.CharField(max_length=3)),
                ('propuestaAgenda', models.CharField(max_length=500)),
                ('ponos', models.CharField(max_length=50)),
                ('nproyecto', models.PositiveIntegerField()),
                ('clienteIntercompannia', models.CharField(max_length=50)),
                ('notasExtras', models.CharField(max_length=50)),
                ('estadoActual', models.CharField(max_length=50)),
                ('aprobadoJefatura', models.CharField(max_length=50)),
                ('aprobadoGerencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
